import React, {useEffect, useRef, useState} from 'react';
import {ArrowUpRight, ArrowRight, Search, Plus, Minus, X, ShoppingBag, Menu, MapPin, Phone, Leaf, Clock, ChevronLeft, ChevronRight, Check, UtensilsCrossed} from 'lucide-react';
import {business, dishes, menuPages, Dish} from './data/siteData';
import {openingStatus} from './utils/openingStatus';
type Bag = Record<string, number>;
const money = (n:number) => new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(n);
function readBag():Bag {try {const b=JSON.parse(localStorage.getItem('vq-bag-v2')||'{}'); return Object.fromEntries(Object.entries(b).filter(([id,q])=>dishes.some(d=>d.id===id)&&Number.isInteger(q)&&Number(q)>0&&Number(q)<=99)) as Bag;}catch{return {};}}
const media=(file:string)=>`/media/${file}`;
function External({href,children,className=''}:React.PropsWithChildren<{href:string;className?:string}>) {return <a href={href} target="_blank" rel="noreferrer" className={className}>{children}</a>;}
export default function App(){
  const [bag,setBag]=useState<Bag>(readBag), [drawer,setDrawer]=useState(false),[mobile,setMobile]=useState(false);
  const [query,setQuery]=useState(''),[category,setCategory]=useState('All dishes'),[diet,setDiet]=useState(false);
  const [status,setStatus]=useState(()=>openingStatus()),[page,setPage]=useState<number|null>(null),[toast,setToast]=useState('');
  const dialog=useRef<HTMLDialogElement>(null), bagDialog=useRef<HTMLDialogElement>(null);
  const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const visible=dishes.filter(d=>(category==='All dishes'||d.category===category)&&(!diet||d.option==='Vegan option')&&normalize(`${d.name} ${d.vietnamese} ${d.description}`).includes(normalize(query)));
  const count=Object.values(bag).reduce((a,b)=>a+b,0), total=dishes.reduce((s,d)=>s+d.price*(bag[d.id]||0),0);
  useEffect(()=>{try{localStorage.setItem('vq-bag-v2',JSON.stringify(bag));}catch{}},[bag]);
  useEffect(()=>{const t=setInterval(()=>setStatus(openingStatus()),30000);const sync=(e:StorageEvent)=>{if(e.key==='vq-bag-v2')setBag(readBag());};window.addEventListener('storage',sync);return()=>{clearInterval(t);window.removeEventListener('storage',sync);};},[]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),2500);return()=>clearTimeout(t);},[toast]);
  useEffect(()=>{if(page!==null)dialog.current?.showModal();else dialog.current?.close();},[page]);
  useEffect(()=>{if(drawer)bagDialog.current?.showModal();else bagDialog.current?.close();},[drawer]);
  useEffect(()=>{document.body.style.overflow=drawer||page!==null?'hidden':'';return()=>{document.body.style.overflow='';};},[drawer,page]);
  const update=(id:string,delta:number)=>setBag(prev=>{const next={...prev};next[id]=Math.min(99,Math.max(0,(next[id]||0)+delta));if(!next[id])delete next[id];return next;});
  const add=(d:Dish)=>{update(d.id,1);setToast(`${d.name} added to your list`);};
  async function copyList(){const text=`Việt Quán takeaway list\n${dishes.filter(d=>bag[d.id]).map(d=>`${bag[d.id]} × ${d.name} — ${money(d.price*bag[d.id])}`).join('\n')}\nEstimated total: ${money(total)} AUD\nPlease confirm prices, availability and pickup time by phone.`;try{await navigator.clipboard.writeText(text);setToast('Takeaway list copied');}catch{setToast('Copy unavailable. Your list is shown here for your call.');}}
  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <div className="announcement"><span>VIETNAMESE NOODLE HOUSE</span><span>Bicton, Western Australia</span></div>
    <header className="header site-header"><a href="#" className="brand" aria-label="Việt Quán home"><img src={media('viet-quan-logo.svg')} alt="Việt Quán"/><span className="brand-wordmark">VIỆT QUÁN<small>NOODLE HOUSE · BICTON</small></span></a><nav aria-label="Main navigation" className={mobile?'nav expanded':'nav'}>{[['menu','Our menu'],['story','Our place'],['visit','Visit us']].map(([id,label])=><a key={id} href={`#${id}`} onClick={()=>setMobile(false)}>{label}</a>)}</nav><div className="nav-actions"><button className="bag-btn" onClick={()=>setDrawer(true)} aria-label={`Open takeaway list, ${count} items`}><ShoppingBag size={18}/><span className="bag-count">{count}</span></button><External href={business.booking} className="button dark nav-book">Book a table <ArrowUpRight size={16}/></External><button className="menu-toggle icon-btn" aria-label="Toggle navigation" aria-expanded={mobile} onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></div></header>
    <main id="main">
      <section className="hero reference-hero" aria-label="Welcome to Việt Quán">
        <div className="hero-copy">
          <p className="eyebrow">A TASTE OF VIETNAM, RIGHT HERE IN BICTON</p>
          <h1>VIỆT QUÁN<em>Phở and more.</em></h1>
          <p>Fragrant broth. Fresh herbs. Flavours to come home to.<br/>Your neighbourhood noodle house at Hawaiian’s Melville.</p>
          <div className="hero-actions">
            <a href="#menu" className="button">Explore menu <ArrowRight size={17}/></a>
            <div className="hero-price"><span>Dine in<br/>or take away</span></div>
          </div>
        </div>
        <div className="hero-visual">
          <div className="hero-colour-circle" aria-hidden="true"/>
          <img className="hero-photo" src={media('hero-food-clean.png')} alt="Wok-tossed noodles, shown in the restaurant’s supplied WhatsApp video" fetchPriority="high"/>
          
          <span className="hero-dish-caption">WOK-TOSSED NOODLES · FROM OUR TABLE</span>
        </div>
        <div className="hero-bottom">
          <External href={business.maps} className="hero-rating"><span className="stars" aria-label="Rated 4.7 out of 5">★★★★★</span><span>4.7 · 106 Google reviews</span><ArrowUpRight size={13}/></External>
          <div className="live-status"><span className={`status-dot ${status.open?'open':''}`}/><span>{status.label} · Perth time</span></div>
          <a href="#menu" className="hero-scroll">DISCOVER THE MENU <span className="scroll-track"/></a>
        </div>
      </section>
      <div className="values-strip"><span><UtensilsCrossed/>Vietnamese favourites</span><i>✳</i><span><Leaf/>Fresh, vibrant flavours</span><i>✳</i><span><ShoppingBag/>Dine in or take away</span><i>✳</i><span><MapPin/>Your neighbourhood noodle house</span></div>
      <section className="section favourites"><div className="section-heading"><div><p className="eyebrow">THE FIRST THING WE’D ORDER</p><h2>Find your new <em>favourite.</em></h2></div><a className="text-link" href="#menu">Discover the menu <ArrowUpRight size={18}/></a></div><div className="dish-cards">{[dishes[1],dishes[6],dishes[4]].map((d,i)=><article className="feature-card" key={d.id}><div className="card-photo"><img src={media(`${d.image}.webp`)} alt={d.name} loading="lazy"/><span className="dish-number">0{i+1} / {i===0?'THE CLASSIC':i===1?'SOMETHING HEARTY':'FRESH & VIBRANT'}</span><button className="round-add" onClick={()=>add(d)} aria-label={`Add ${d.name} to takeaway list`}><Plus/></button></div><div className="card-title"><h3>{d.name}</h3><span>{money(d.price)}</span></div><p>{d.description}</p></article>)}</div></section>
      <section id="menu" className="menu-section section"><div className="section-heading"><div><p className="eyebrow">FROM OUR KITCHEN</p><h2>A little something<br/><em>for every craving.</em></h2></div><div className="menu-intro"><p>From comforting noodle bowls to wok-tossed favourites. Explore a selection below, or open our photographed menu.</p><button className="text-link" onClick={()=>setPage(0)}>View the original menu <ArrowUpRight size={18}/></button></div></div><div className="menu-toolbar"><div className="categories" aria-label="Menu category">{['All dishes','Noodle bowls','Rice dishes'].map(c=><button className={category===c?'active':''} aria-pressed={category===c} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div><label className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find your favourite…" aria-label="Search dishes"/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}><X size={15}/></button>}</label></div><div className="menu-meta"><span>{visible.length} dishes · Prices in AUD</span><label><input type="checkbox" checked={diet} onChange={e=>setDiet(e.target.checked)}/><Leaf size={14}/> Vegan option</label></div><div className="menu-grid">{visible.map(d=><article className="menu-item" key={d.id}><div><span className="vn-name">{d.vietnamese}</span><h3>{d.name}</h3><p>{d.description}</p>{d.option&&<span className="diet-note">{d.option}</span>}</div><div className="menu-item-action"><strong>{money(d.price)}</strong><button className="small-add" aria-label={`Add ${d.name} to takeaway list`} onClick={()=>add(d)}>{bag[d.id]?<><Check size={16}/><span>{bag[d.id]}</span></>:<Plus size={19}/>}</button></div></article>)}</div>{!visible.length&&<div className="empty-state"><Search/><h3>No dishes found</h3><p>Try another dish or explore all of our favourites.</p><button className="button dark" onClick={()=>{setQuery('');setDiet(false);setCategory('All dishes');}}>Reset filters</button></div>}<div className="menu-footnote"><Leaf size={20}/><p>Made for your table. Please tell our team about allergies and dietary needs. Gluten-free and vegan options require a request. Our kitchen handles nuts, gluten and other allergens. Prices follow the supplied menu; confirm current prices when ordering. A 10% public holiday surcharge applies.</p></div><div className="menu-originals">{menuPages.slice(0,4).map((p,i)=><button key={p.src} onClick={()=>setPage(i)}><img src={media(p.src)} alt={`${p.name} printed menu`} loading="lazy"/><span>{p.name}<ArrowUpRight size={16}/></span></button>)}</div></section>
      <section id="story" className="story section"><div className="story-visual"><img src={media('map-0.webp')} alt="The green entrance doors of Việt Quán in Hawaiian’s Melville" loading="lazy"/><span className="vertical-note">A WARM WELCOME, EVERY TIME.</span></div><div className="story-copy"><p className="eyebrow">XIN CHÀO, BICTON</p><h2>A taste of Vietnam.<br/><em>A place to belong.</em></h2><p>There’s something special about a table filled with good food. A steaming bowl of noodles. Fresh herbs passed around. One more bite before the conversation moves on.</p><p>At Việt Quán, we bring the flavours of Vietnam to Hawaiian’s Melville. Drop in for lunch, gather your favourite people for dinner, or take a little comfort home.</p><div className="story-signoff">From street food classics to home-style favourites.</div><External href={business.booking} className="button dark">Make yourself at home <ArrowUpRight size={18}/></External></div></section>
      <section className="film-section"><div className="film-copy"><p className="eyebrow">A CLOSER LOOK</p><h2>Pull up <em>a chair.</em></h2><p>From the wok to the table. A little glimpse of Việt Quán, before your next visit.</p></div><video controls playsInline preload="none" poster={media('video-poster.jpg')} aria-label="Việt Quán food video: wok-tossed noodles and freshly served phở"><source src={media('restaurant.mp4')} type="video/mp4"/>Your browser does not support video playback.</video></section>
      <section className="review-strip section"><div><p className="eyebrow">A NEIGHBOURHOOD FAVOURITE</p><h2>Good food brings<br/><em>people back.</em></h2></div><div className="review-score"><span>4.7<span className="out-of">/5</span></span><div className="stars">★★★★★</div><p>106 reviews on Google</p><small>Checked 12 September 2026</small></div><External className="button outline" href={business.maps}>Read our Google reviews <ArrowUpRight size={18}/></External></section>
      <section id="visit" className="visit section"><div><p className="eyebrow">WE’LL SAVE YOU A SEAT</p><h2>Your next good meal<br/><em>is right here.</em></h2><div className="visit-details"><div><MapPin/><div><h3>Find us in Bicton</h3><p>Hawaiian’s Melville<br/>{business.address}</p><External href={business.maps} className="text-link">Get directions <ArrowUpRight size={16}/></External></div></div><div><Clock/><div><h3>Come by for lunch or dinner</h3><p>Tuesday – Sunday · 11am – 9pm<br/>Monday · Closed</p><small>Public holiday hours may vary. Please call to check.</small><div className="visit-status"><span className={`status-dot ${status.open?'open':''}`}/>{status.label}</div></div></div><div><Phone/><div><h3>Let’s make a plan</h3><a href={`tel:${business.tel}`} className="phone-link">{business.phone}</a><p>Call for takeaway, group bookings or dietary questions.</p></div></div></div><External href={business.booking} className="button dark">Book a table on Google <ArrowUpRight size={18}/></External></div><div className="visit-image"><img src={media('map-0.webp')} alt="Look for Việt Quán’s distinctive green doorway at Hawaiian’s Melville" loading="lazy"/><div className="visit-image-caption"><span>LOOK FOR THE GREEN DOOR</span><strong>See you at Việt Quán.</strong><External href={business.maps}>Hawaiian’s Melville <ArrowUpRight size={18}/></External></div></div></section>
      <section className="faq section"><p className="eyebrow">BEFORE YOU VISIT</p><h2>A few helpful things.</h2>{[['Can I order takeaway?','Yes. Build a takeaway list using the + buttons, then call us to confirm your dishes, current prices and collection time. Your list is saved on this device; it is not sent to the kitchen.'],['How do I reserve a table?','Use “Book a table” to check the restaurant’s booking page on Google, or call +61 429 013 944. Your booking is confirmed by the booking provider or our team.'],['Do you cater for dietary requirements?','Our printed menu marks gluten-free options (GFO) and vegan options (VGO). Please ask our team before ordering. All dishes are prepared in a kitchen where nuts, gluten and other allergens are present.']].map(([q,a])=><details key={q}><summary>{q}<Plus size={18}/></summary><p>{a}</p></details>)}</section>
    </main><footer><div className="footer-main"><div><img src={media('viet-quan-logo.svg')} alt="Việt Quán"/><p>Vietnamese flavours. Bicton heart.</p></div><div><span>COME ON OVER</span><p>Hawaiian’s Melville<br/>{business.address}</p></div><div><span>SAY XIN CHÀO</span><a href={`tel:${business.tel}`}>{business.phone}</a><External href={business.maps}>Find us on Google Maps <ArrowUpRight size={14}/></External></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Việt Quán.</span><span>Restaurant photography via <External href="https://maps.app.goo.gl/5MCKpLVNwbaKKP3N6">Google Maps</External> · <External href="https://maps.app.goo.gl/K1cxtakbnKwzMUxk6">More photos</External></span></div></footer>
    <div className="mobile-bar"><a href={`tel:${business.tel}`}><Phone size={17}/>Call us</a><External href={business.booking}>Book a table <ArrowUpRight size={16}/></External><button onClick={()=>setDrawer(true)}><ShoppingBag size={17}/>Your list ({count})</button></div><div aria-hidden={!toast || drawer} className={`toast ${toast?'shown':''}`} role="status">{toast}<button tabIndex={toast && !drawer ? 0 : -1} onClick={()=>{setDrawer(true);setToast('');}}>View list <ArrowRight size={15}/></button></div>
    <dialog ref={dialog} className="menu-dialog" aria-label="Original restaurant menu" onCancel={()=>setPage(null)} onClick={e=>{if(e.target===e.currentTarget)setPage(null);}}><div className="dialog-top"><div><span className="eyebrow">THE ORIGINAL MENU</span><h2>{menuPages[page??0].name}</h2></div><button className="icon-btn" onClick={()=>setPage(null)} aria-label="Close menu viewer"><X/></button></div><img className="full-menu" src={media(menuPages[page??0].src)} alt={`${menuPages[page??0].name} original printed menu, including prices`}/><div className="viewer-controls"><button aria-label="Previous menu page" onClick={()=>setPage(p=>((p??0)-1+menuPages.length)%menuPages.length)}><ChevronLeft/></button><span>{(page??0)+1} / {menuPages.length}</span><a href={media(menuPages[page??0].src)} target="_blank" rel="noreferrer">Open full size <ArrowUpRight size={15}/></a><button aria-label="Next menu page" onClick={()=>setPage(p=>((p??0)+1)%menuPages.length)}><ChevronRight/></button></div></dialog>
    <dialog ref={bagDialog} className="bag-dialog" aria-label="Your takeaway list" onCancel={()=>setDrawer(false)} onClick={e=>{if(e.target===e.currentTarget)setDrawer(false);}}><div className="bag-content"><div className="dialog-top"><div><span className="eyebrow">A LITTLE COMFORT TO GO</span><h2>Your takeaway list <span>({count})</span></h2></div><button className="icon-btn" onClick={()=>setDrawer(false)} aria-label="Close takeaway list"><X/></button></div><div className="bag-body">{count===0?<div className="empty-state"><ShoppingBag size={38}/><h3>What are you craving?</h3><p>Add a few favourites, then call us to order.</p><button className="button dark" onClick={()=>{setDrawer(false);location.hash='menu';}}>Explore the menu <ArrowRight size={17}/></button></div>:<>{dishes.filter(d=>bag[d.id]).map(d=><article className="bag-item" key={d.id}><div><h3>{d.name}</h3><p>{money(d.price)} each</p><div className="quantity"><button aria-label={`Decrease ${d.name}`} onClick={()=>update(d.id,-1)}><Minus size={15}/></button><span>{bag[d.id]}</span><button aria-label={`Increase ${d.name}`} onClick={()=>update(d.id,1)} disabled={bag[d.id]>=99}><Plus size={15}/></button></div></div><strong>{money(d.price*bag[d.id])}</strong></article>)}<button className="text-link clear-list" onClick={()=>setBag({})}>Clear list</button></>}</div>{count>0&&<div className="bag-bottom"><div className="subtotal"><span>Estimated total</span><strong>{money(total)} <small>AUD</small></strong></div><p>This is your saved list, not a placed order. Call to confirm availability, final prices and pickup time. Public holiday surcharge may apply.</p><a className="button dark" href={`tel:${business.tel}`}><Phone size={18}/>Call to place your order</a><button className="button outline" onClick={copyList}>Copy my list</button><p className="copy-status" role="status">{toast}</p><small className="bag-status">{status.label} · regular hours</small></div>}</div></dialog>
  </>;
}
